services:
  - type: web
    name: solocart-frontend
    env: node
    plan: free
    buildCommand: echo "No build step required"
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
